"""A durable, searchable record of what was said to agents and what they said back.

Three things motivated this, and the third is the one that decided the shape.

Sessions are ephemeral by construction. ``next-session.md`` is read once and
deleted; the per-session database does not outlive the session. Closed work is
answerable from ``git log`` and open work from ``backlog/``, but *conversation*
-- the question a human asked, the answer an agent gave, the message one agent
sent another -- has been answerable from nothing. It exists in
``~/.copilot/session-store.db`` and in ``~/.operator/messages/``, in two
different shapes, neither of which is queryable as a conversation.

So this module is a **union view over sources that already exist**, plus a
place for future ones to land. It is deliberately not a new system of record:
everything it holds is a copy, every row names the source it came from, and
re-seeding is idempotent. Losing this database costs a re-seed, not history.

**What is captured, and what is not.** Messages and final responses. Not
reasoning, not tool calls, not deltas. That is a product decision -- the
question "what did I ask, and what came back" is answerable from the endpoints
alone, and the middle is where the volume is.

**The classification is the part worth reviewing.** Everything arriving at an
agent arrives as a "user message", including three things that are not a human
speaking: the operator's launch preamble, peer messages injected by ``operator
send``, and mail delivered at session start. Storing those as human speech
would mean the single question this exists to answer -- *what did I say?* --
returns mostly machine text. :func:`classify` separates them, and
``tests/test_conversation_log.py`` pins each rule against real captured text.
"""
from __future__ import annotations

import hashlib
import json
import re
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

import install_manifest
from project_paths import operator_home

#: Where the conversation database lives. One per machine, beside the rest of
#: the operator's state rather than inside any checkout: it spans projects, and
#: a per-repository copy would fragment exactly the cross-project view that
#: makes it useful.
DB_NAME = "conversations.db"

#: Message came from a person typing.
HUMAN = "human"
#: Message came from another agent -- `operator send`, or delivered mail.
AGENT = "agent"
#: Message was generated by the operator wrapper itself (launch preamble).
SYSTEM = "system"

#: Sent *to* the agent whose session this is.
INBOUND = "inbound"
#: Sent *by* that agent.
OUTBOUND = "outbound"

#: A person and an agent talking.
HUMAN_AGENT = "human-agent"
#: Two agents talking, with no human in the exchange.
AGENT_AGENT = "agent-agent"

SOURCE_SESSION_STORE = "session-store"
SOURCE_OPERATOR_MAIL = "operator-mail"
SOURCE_HOOK = "hook"

SCHEMA = """
CREATE TABLE IF NOT EXISTS messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    source      TEXT NOT NULL,
    source_id   TEXT NOT NULL,
    project     TEXT NOT NULL DEFAULT '',
    repository  TEXT NOT NULL DEFAULT '',
    cwd         TEXT NOT NULL DEFAULT '',
    branch      TEXT NOT NULL DEFAULT '',
    session_id  TEXT NOT NULL DEFAULT '',
    instance    TEXT NOT NULL DEFAULT '',
    channel     TEXT NOT NULL,
    direction   TEXT NOT NULL,
    actor       TEXT NOT NULL,
    sender      TEXT NOT NULL DEFAULT '',
    recipient   TEXT NOT NULL DEFAULT '',
    body        TEXT NOT NULL,
    asks        INTEGER NOT NULL DEFAULT 0,
    sent_at     TEXT NOT NULL,
    captured_at TEXT NOT NULL,
    UNIQUE (source, source_id)
);
CREATE INDEX IF NOT EXISTS messages_sent_at ON messages (sent_at);
CREATE INDEX IF NOT EXISTS messages_project ON messages (project, sent_at);
CREATE INDEX IF NOT EXISTS messages_channel ON messages (channel, sent_at);
"""

# The FTS mirror is created separately: FTS5 is a compile-time option, and a
# Python whose sqlite3 lacks it must still be able to use everything else here.
# `search_mode` reports which is in force rather than degrading quietly -- a
# substring fallback silently answering fewer queries than the caller thinks is
# the failure this project keeps finding in other guises.
FTS_SCHEMA = """
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts
    USING fts5(body, content='messages', content_rowid='id');
CREATE TRIGGER IF NOT EXISTS messages_ai AFTER INSERT ON messages BEGIN
    INSERT INTO messages_fts (rowid, body) VALUES (new.id, new.body);
END;
CREATE TRIGGER IF NOT EXISTS messages_ad AFTER DELETE ON messages BEGIN
    INSERT INTO messages_fts (messages_fts, rowid, body)
        VALUES ('delete', old.id, old.body);
END;
CREATE TRIGGER IF NOT EXISTS messages_au AFTER UPDATE ON messages BEGIN
    INSERT INTO messages_fts (messages_fts, rowid, body)
        VALUES ('delete', old.id, old.body);
    INSERT INTO messages_fts (rowid, body) VALUES (new.id, new.body);
END;
"""


class ConversationError(RuntimeError):
    """The conversation store could not be opened, read or written."""


# --------------------------------------------------------------------------
# Location
# --------------------------------------------------------------------------

def db_path(home: "Path | None" = None) -> Path:
    return (Path(home) if home is not None else operator_home()) / DB_NAME


def copilot_home() -> Path:
    """Where the Copilot CLI keeps its own session store.

    Spelled as ``Path.home() / ".copilot"`` to match every other reference to
    it in this repository (``copilot_operator.py``, ``setup_tools.py``,
    ``project_instructions.py``), so a test that relocates ``Path.home``
    relocates this too.

    :func:`operator_home` is imported from ``project_paths`` rather than
    re-implemented for the same reason. This module's first draft carried its
    own ``OPERATOR_HOME`` lookup while the rest of the toolkit reads
    ``COPILOT_OPERATOR_HOME`` -- so a run with a relocated state tree moved
    everything *except* the conversation store, which went on writing to the
    developer's real one while reading mail from the temporary one. Nothing
    could report that, because each half was individually correct.
    """
    return Path.home() / ".copilot"


# --------------------------------------------------------------------------
# Connection
# --------------------------------------------------------------------------

def connect(path: "Path | None" = None) -> sqlite3.Connection:
    """Open the store, creating it if absent.

    WAL is set because the writer is a Copilot extension running inside a live
    session while a human may have the viewer open on the same file. The
    default rollback journal makes those two block each other; a capture hook
    that stalls a session because somebody is reading a web page would be a bad
    trade for a log.
    """
    target = Path(path) if path is not None else db_path()
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(target))
    except (OSError, sqlite3.Error) as exc:
        raise ConversationError(f"could not open {target}: {exc}") from exc
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA journal_mode=WAL")
        conn.executescript(SCHEMA)
        try:
            existing = conn.execute(
                "SELECT 1 FROM sqlite_master"
                " WHERE type='table' AND name='messages_fts'").fetchone()
            conn.executescript(FTS_SCHEMA)
            if not existing:
                # The index is only populated by the triggers, and the triggers
                # only exist from here on. Rows already in `messages` were
                # never indexed, so without this the store answers every search
                # with nothing -- silently, and most convincingly on the
                # machine with the most history.
                #
                # Reachable two ways: a store created by a Python whose sqlite3
                # lacks FTS5 and later opened by one that has it, and a store
                # created before this table existed at all. Rebuilding costs a
                # single pass, once, at the transition.
                conn.execute(
                    "INSERT INTO messages_fts (messages_fts) VALUES ('rebuild')")
        except sqlite3.Error:
            # No FTS5 in this interpreter's sqlite3. Everything else works;
            # `search_mode` will report the substring fallback.
            pass
        conn.commit()
    except sqlite3.Error as exc:
        raise ConversationError(f"could not initialise {target}: {exc}") from exc
    return conn


def search_mode(conn: sqlite3.Connection) -> str:
    """``"fts"`` when full-text search is available, else ``"substring"``.

    Reported to the caller and rendered in the viewer, deliberately. The two
    modes answer different queries -- FTS tokenises and matches word prefixes,
    a LIKE scan does neither -- and a viewer that silently returned fewer
    results on one machine than another would be indistinguishable from having
    fewer messages.

    The question is asked by *running* a trivial MATCH rather than by looking
    the table up in ``sqlite_master``. Presence in the catalogue is not
    usability: a store created by a build with FTS5 and opened by one without
    still lists ``messages_fts``, so the catalogue answers "fts" and every
    search then fails with ``no such module: fts5``. A probe cannot be wrong
    about the thing it just did.
    """
    try:
        conn.execute(
            "SELECT rowid FROM messages_fts WHERE messages_fts MATCH ? LIMIT 1",
            ('"a"',)).fetchone()
    except sqlite3.Error:
        return "substring"
    return "fts"


# --------------------------------------------------------------------------
# Classification
# --------------------------------------------------------------------------

#: The operator's launch preamble. Matched on a phrase that has been stable
#: across every version of `build_preamble` and is specific enough that no
#: human types it.
PREAMBLE_MARKER = "You are running under an automated operator wrapper"

#: How `operator send` renders a peer message into the receiving agent's
#: prompt stream. Captured verbatim from delivered messages.
#:
#: Deliberately *not* anchored with ``^``. The anchor belongs in exactly one
#: place, and it is the ``.match()`` in :func:`peer_sender`; with both,
#: swapping that for ``.search()`` changes nothing and no test can object --
#: so the redundancy reads as safety while quietly retiring the guarantee that
#: a human quoting a peer message is still filed as a human.
PEER_PREFIX_RE = re.compile(r'\s*\[operator message from ["\u201c]([^"\u201d]+)["\u201d]\]')


def peer_sender(body: str) -> "str | None":
    """The peer that sent this, if the text is an injected peer message.

    Used to *decline* to store it. ``operator send`` persists every message it
    delivers -- 284 of the 286 mail files on this machine are ``delivery:
    "live"`` -- so the copy that lands in the receiving agent's prompt stream
    is the second record of a message the mail store already holds, with worse
    fields: no recipient, no delivery state, and a timestamp describing when it
    was *read* rather than when it was sent.

    Mail owns inter-agent messages, in both the seeder and the capture hook.
    One rule in one place, rather than two paths that agree until one is
    edited.
    """
    match = PEER_PREFIX_RE.match(body or "")
    return match.group(1) if match else None


#: A `<system_reminder>` block. The CLI appends these to a user turn to
#: re-state project instructions, and they arrive inside the "user message"
#: exactly as the operator preamble does.
_REMINDER_RE = re.compile(r"<system_reminder>.*?</system_reminder>", re.S)


def is_only_machine_text(body: str) -> bool:
    """True when nothing is left after removing the CLI's own insertions.

    Measured on the real store before this existed: 462 of 1918 rows filed as
    human speech -- 24% -- were `<system_reminder>` blocks and **nothing
    else**. Not one of the 462 contained a word the human typed. Asked "what
    did I say", the store answered with a quarter of its own instruction
    files.

    The test is "what remains", not "does it start with one". None of the 462
    started with the tag, because the CLI puts a newline first, so a prefix
    check finds zero of them and reports the corpus clean. It is also why a
    message that is *partly* a reminder stays human: the reminder is appended
    to something a person wrote, and dropping that would trade this failure
    for its mirror image.
    """
    return bool(body) and not _REMINDER_RE.sub("", body).strip()


def classify(body: str) -> "tuple[str, str, str]":
    """Who really said this: ``(actor, channel, sender)``.

    Everything reaching an agent arrives as a "user message", which is a fact
    about the transport and not about who spoke. On this machine 1378 of 3527
    recorded "user messages" are the operator's own launch preamble and a
    further 238 are peer messages injected by ``operator send`` -- so filed as
    human speech, 46% of the record is machine text, and the single question
    the store exists to answer (*what did I say?*) returns mostly noise.

    Mail delivered at session start needs no rule here: ``render_for_agent``
    appends it to the preamble, so it arrives inside a preamble turn and is
    already classified by the first branch. A separate detector for it would
    match nothing -- and a detector that never fires reports the whole corpus
    clean, which reads exactly like success.
    """
    text = body or ""
    if PREAMBLE_MARKER in text[:400]:
        return SYSTEM, HUMAN_AGENT, "operator"
    if is_only_machine_text(text):
        return SYSTEM, HUMAN_AGENT, "copilot-cli"
    sender = peer_sender(text)
    if sender is not None:
        return AGENT, AGENT_AGENT, sender
    return HUMAN, HUMAN_AGENT, ""


#: A question mark outside a fenced code block. Deliberately a heuristic, and
#: named as one: the viewer offers it as a filter ("show me where I was asked
#: something"), never as a claim that the message *is* a question.
_FENCE_RE = re.compile(r"```.*?```", re.S)


def asks_question(body: str) -> bool:
    return "?" in _FENCE_RE.sub(" ", body or "")


def project_of(repository: str, cwd: str) -> str:
    """A short, stable project name for grouping.

    Prefers the repository name because it survives the same project being
    checked out at two paths -- which is the normal case here, since every
    agent works in ``<repo>/.worktrees/<branch>``. Falls back to the directory
    name, with worktree suffixes stripped, so a worktree groups with its parent
    instead of appearing as its own project.
    """
    if repository:
        return repository.rstrip("/").split("/")[-1]
    if not cwd:
        return ""
    parts = [p for p in re.split(r"[\\/]+", cwd.rstrip("\\/")) if p]
    if not parts:
        return ""
    # <repo>/.worktrees/<name> -> <repo>
    for i, part in enumerate(parts):
        if part == ".worktrees" and i > 0:
            return parts[i - 1]
    return parts[-1]


def _utc(value: str) -> str:
    """Normalise a timestamp to ``YYYY-MM-DDTHH:MM:SSZ``, or "" if unreadable.

    Two spellings arrive: SQLite's ``'YYYY-MM-DD HH:MM:SS'`` from the session
    store and ISO-8601 with a ``Z`` from operator mail. Storing them as written
    means a lexical ``ORDER BY`` interleaves them wrongly at the exact place
    the viewer sorts, so both are converted once, on the way in.
    """
    text = (value or "").strip()
    if not text:
        return ""
    candidate = text.replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(candidate)
    except ValueError:
        try:
            parsed = datetime.strptime(text[:19], "%Y-%m-%d %H:%M:%S")
        except ValueError:
            return ""
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------
# Writing
# --------------------------------------------------------------------------

_COLUMNS = ("source", "source_id", "project", "repository", "cwd", "branch",
            "session_id", "instance", "channel", "direction", "actor",
            "sender", "recipient", "body", "asks", "sent_at", "captured_at")


def record(conn: sqlite3.Connection, *, source: str, source_id: str,
           body: str, direction: str, sent_at: str,
           project: str = "", repository: str = "", cwd: str = "",
           branch: str = "", session_id: str = "", instance: str = "",
           channel: "str | None" = None, actor: "str | None" = None,
           sender: str = "", recipient: str = "") -> bool:
    """Store one message. Returns ``True`` if it was new.

    ``INSERT OR IGNORE`` against ``UNIQUE (source, source_id)`` is what makes
    seeding re-runnable: the user asked to seed manually on each machine, which
    means it will be run more than once on the same data, and a seeder that
    duplicates on the second run is one nobody can safely repeat.
    """
    text = body or ""
    if not text.strip():
        return False
    guessed_actor, guessed_channel, guessed_sender = classify(text)
    if direction == OUTBOUND:
        # The agent speaking. Channel is inherited from whoever it is
        # answering, which the caller knows and this function does not.
        guessed_actor = AGENT
        guessed_channel = channel or HUMAN_AGENT
        guessed_sender = sender
    row = {
        "source": source, "source_id": source_id,
        "project": project or project_of(repository, cwd),
        "repository": repository, "cwd": cwd, "branch": branch,
        "session_id": session_id, "instance": instance,
        "channel": channel or guessed_channel,
        "direction": direction,
        "actor": actor or guessed_actor,
        "sender": sender or guessed_sender,
        "recipient": recipient,
        "body": text,
        "asks": 1 if asks_question(text) else 0,
        "sent_at": _utc(sent_at) or now_utc(),
        "captured_at": now_utc(),
    }
    placeholders = ", ".join(":" + c for c in _COLUMNS)
    cur = conn.execute(
        f"INSERT OR IGNORE INTO messages ({', '.join(_COLUMNS)}) "
        f"VALUES ({placeholders})", row)
    if cur.rowcount > 0:
        return True
    # Already stored. Re-apply the classification, because the *rules* change
    # and the messages do not: `classify` learning that a body is machine text
    # must be able to reach the rows already filed under the old answer.
    #
    # Without this, seeding is idempotent in the unhelpful direction -- a fixed
    # rule leaves every previously-misfiled row misfiled, and the only remedy
    # is knowing to delete the database, which is exactly the kind of thing
    # nobody knows. Measured when it mattered: a quarter of the "human" rows on
    # this machine were the CLI's own instruction files.
    #
    # The body is deliberately not rewritten. A message's text is what was
    # said; only the verdict about it is ours to revise.
    conn.execute(
        "UPDATE messages SET channel = :channel, actor = :actor,"
        " sender = :sender, asks = :asks"
        " WHERE source = :source AND source_id = :source_id"
        "   AND (channel != :channel OR actor != :actor"
        "        OR sender != :sender OR asks != :asks)", row)
    return False


# --------------------------------------------------------------------------
# Seeding: the Copilot session store
# --------------------------------------------------------------------------

class SeedReport:
    """What a seed run did, in enough detail to be worth reading twice.

    Two fields carry most of the weight.

    ``skipped`` distinguishes "nothing new" from "silently rejected
    everything", which are the two outcomes a re-run exists to tell apart.

    ``absent`` separates *this source is not on this machine* from *this source
    is here and would not read*. Only the second is a failure. A machine that
    has never run a peer agent has no mail directory, and a seeder that exits
    non-zero over it is one that fails on a clean install -- while a mail
    directory that exists and throws is exactly the case that must not be
    swallowed.
    """

    def __init__(self, source: str) -> None:
        self.source = source
        self.added = 0
        self.duplicate = 0
        self.skipped: dict[str, int] = {}
        self.errors: list[str] = []
        self.absent: str = ""

    def skip(self, reason: str) -> None:
        self.skipped[reason] = self.skipped.get(reason, 0) + 1

    @property
    def failed(self) -> bool:
        return bool(self.errors)

    def describe(self) -> str:
        if self.absent and not self.errors:
            return f"{self.source}: nothing to read ({self.absent})"
        parts = [f"{self.source}: {self.added} added",
                 f"{self.duplicate} already present"]
        for reason, count in sorted(self.skipped.items()):
            parts.append(f"{count} skipped ({reason})")
        if self.errors:
            parts.append(f"{len(self.errors)} error(s)")
        return ", ".join(parts)


def _body_key(body: str) -> str:
    """A message's identity for cross-source matching.

    Whitespace-normalised: the two sources quote the same text but need not
    agree on trailing newlines, and a mismatch here costs a duplicate rather
    than a loss, so the normalisation is deliberately mild.
    """
    return hashlib.sha256(" ".join((body or "").split()).encode("utf-8")).hexdigest()


def _hook_index(conn: sqlite3.Connection) -> set:
    """``(session_id, direction, body key)`` for everything the hook captured.

    Read once per seed rather than queried per turn; the store is a few
    thousand rows on the machine that has been running longest.
    """
    return {
        (r["session_id"] or "", r["direction"], _body_key(r["body"]))
        for r in conn.execute(
            "SELECT session_id, direction, body FROM messages WHERE source = ?",
            (SOURCE_HOOK,))
    }


def seed_session_store(conn: sqlite3.Connection,
                       store: "Path | None" = None) -> SeedReport:
    """Copy human/agent turns out of the Copilot CLI's own session store.

    Read-only, and opened read-only: this is somebody else's live database and
    the tool has no business being able to write to it even by mistake.
    """
    report = SeedReport(SOURCE_SESSION_STORE)
    path = Path(store) if store is not None else copilot_home() / "session-store.db"
    present = install_manifest.file_present(path)
    if present is False:
        report.absent = f"no session store at {path}"
        return report
    if present is None:
        # Occupied but unexaminable. Reporting that as absent would say "you
        # have no session history" about a machine that has years of it, and
        # `absent` is the answer that exits 0 -- so the wrong branch here is
        # silent data loss dressed as a clean install.
        report.errors.append(
            f"could not determine whether {path} exists (permissions?)")
        return report
    try:
        src = sqlite3.connect(f"file:{path.as_posix()}?mode=ro", uri=True)
    except sqlite3.Error as exc:
        report.errors.append(f"could not open {path}: {exc}")
        return report
    src.row_factory = sqlite3.Row
    try:
        rows = src.execute(
            "SELECT t.session_id, t.turn_index, t.user_message,"
            "       t.assistant_response, t.timestamp,"
            "       s.repository, s.cwd, s.branch"
            "  FROM turns t LEFT JOIN sessions s ON s.id = t.session_id"
            " ORDER BY t.session_id, t.turn_index").fetchall()
    except sqlite3.Error as exc:
        report.errors.append(f"could not read turns: {exc}")
        src.close()
        return report

    # What the capture hook already holds, so the same sentence is not filed
    # twice under two sources.
    #
    # Both sources see the identical turn: the CLI writes it to its own session
    # store, and the extension appends it to the spool. `UNIQUE (source,
    # source_id)` cannot notice, because the two ids are unrelated and `source`
    # differs -- so every turn captured live appeared twice, once the extension
    # was installed. That is the promise this store is for.
    #
    # Matched per message rather than per session, deliberately. Skipping a
    # whole session the hook had *partly* seen would drop the turns from before
    # the extension was installed, and a gap is worse than a duplicate here: a
    # duplicate is visible noise, a gap is invisible loss.
    covered = _hook_index(conn)

    for row in rows:
        context = {
            "repository": row["repository"] or "",
            "cwd": row["cwd"] or "",
            "branch": row["branch"] or "",
            "session_id": row["session_id"] or "",
        }
        stamp = row["timestamp"] or ""
        prompt = row["user_message"] or ""
        actor, channel, sender = classify(prompt)
        session = row["session_id"] or ""
        if channel == AGENT_AGENT:
            # Owned by the mail store; see peer_sender().
            report.skip("peer message, held by operator mail")
        elif not prompt.strip():
            report.skip("empty prompt")
        elif (session, INBOUND, _body_key(prompt)) in covered:
            report.skip("already captured live")
        else:
            added = record(
                conn, source=SOURCE_SESSION_STORE,
                source_id=f'{row["session_id"]}:{row["turn_index"]}:in',
                body=prompt, direction=INBOUND, sent_at=stamp,
                actor=actor, channel=channel, sender=sender, **context)
            report.added += 1 if added else 0
            report.duplicate += 0 if added else 1

        reply = row["assistant_response"] or ""
        if not reply.strip():
            report.skip("empty response")
            continue
        if (session, OUTBOUND, _body_key(reply)) in covered:
            report.skip("already captured live")
            continue
        added = record(
            conn, source=SOURCE_SESSION_STORE,
            source_id=f'{row["session_id"]}:{row["turn_index"]}:out',
            body=reply, direction=OUTBOUND, sent_at=stamp,
            # A reply inherits the channel of what it answers. Filing it as
            # `human-agent` unconditionally was wrong for exactly the turns the
            # branch above declines to store: the peer's message is held by
            # mail, but the agent's answer to it was still landing in the
            # human's conversation, which is the one view the human asked to
            # keep separate.
            actor=AGENT, channel=channel, recipient=sender, **context)
        report.added += 1 if added else 0
        report.duplicate += 0 if added else 1

    src.close()
    conn.commit()
    return report


# --------------------------------------------------------------------------
# Seeding: operator mail
# --------------------------------------------------------------------------

def seed_operator_mail(conn: sqlite3.Connection,
                       root: "Path | None" = None) -> SeedReport:
    """Copy agent-to-agent mail out of ``~/.operator/messages``.

    Both the inbox and its archive are read. A message is filed once, under its
    own id, so a message that moves from inbox to archive between two runs is
    not counted twice -- which is the normal life of every message here.
    """
    report = SeedReport(SOURCE_OPERATOR_MAIL)
    base = Path(root) if root is not None else operator_home() / "messages"
    present = install_manifest.dir_present(base)
    if present is False:
        report.absent = f"no mail directory at {base}"
        return report
    if present is None:
        report.errors.append(
            f"could not determine whether {base} exists (permissions?)")
        return report
    for path in sorted(set(base.glob("**/*.json"))):
        try:
            msg = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            report.errors.append(f"{path.name}: {exc}")
            continue
        if not isinstance(msg, dict):
            report.skip("not a message object")
            continue
        text = msg.get("text") or ""
        if not str(text).strip():
            report.skip("empty message")
            continue
        # The recipient's inbox names the instance; that is the best "project"
        # signal mail carries, and it is a weak one, so it is stored as the
        # instance and left out of `project` rather than guessed at.
        recipient = str(msg.get("to") or "")
        identity = str(msg.get("id") or "")
        if not identity:
            # Not the filename, which is where this went wrong first: a file
            # moving inbox -> archive is the normal life of every message
            # here, and a rename during that move makes the same message file
            # itself a second time under a second key. The content cannot
            # move, so it is what identifies the message.
            #
            # Length-prefixed rather than joined on a separator. Any separator
            # is ambiguous if a field can contain it, and these are arbitrary
            # strings from another program's JSON: with a plain join,
            # from="a" to="b\0c" and from="a\0b" to="c" produce identical
            # bytes, so two different messages collide onto one key and one is
            # dropped. Duplicating a message is untidy; losing one silently is
            # the failure this whole store exists to prevent.
            #
            # `to_id` is in the key because it is what decides the recipient
            # instance. Leaving it out collapsed two messages that differed
            # only in who they were addressed to -- the same text sent to two
            # agents is the ordinary shape of a broadcast, and one of the two
            # was being dropped.
            fields = [str(msg.get(k) or "")
                      for k in ("from", "to", "to_id", "sent_at")]
            fields.append(str(text))
            blob = "".join(f"{len(f)}:{f}" for f in fields)
            identity = "sha256:" + hashlib.sha256(
                blob.encode("utf-8")).hexdigest()
            report.skip("message had no id; keyed by content")
        added = record(
            conn, source=SOURCE_OPERATOR_MAIL, source_id=identity,
            body=str(text), direction=INBOUND,
            sent_at=str(msg.get("sent_at") or ""),
            channel=AGENT_AGENT, actor=AGENT,
            sender=str(msg.get("from") or ""), recipient=recipient,
            instance=str(msg.get("to_id") or recipient))
        report.added += 1 if added else 0
        report.duplicate += 0 if added else 1
    conn.commit()
    return report


# --------------------------------------------------------------------------
# Seeding: the capture spool
# --------------------------------------------------------------------------

def spool_dir(home: "Path | None" = None) -> Path:
    """Where the capture extension appends what it sees.

    The extension writes JSON lines rather than rows. That keeps every
    classification rule in this module -- a capture path that re-implemented
    them in JavaScript would agree with the seeder right up until one of the
    two was edited -- and an append-only file needs no lock against a viewer
    reading the database.
    """
    return (Path(home) if home is not None else operator_home()) / "conversation-spool"


def _prior_channel(conn: sqlite3.Connection, session: str) -> tuple:
    """``(channel, sender)`` of the last message stored *to* this session.

    The fallback for a reply whose prompt was ingested on an earlier run --
    a session that spanned midnight, or one still running when the last seed
    happened. Returns the human channel when there is nothing to go on, which
    is both the common case and the one a wrong guess costs least.

    It cannot recover a peer prompt: those are declined on purpose and held by
    mail, so no row exists to find. Within a run the in-memory map covers that;
    across runs a reply to a peer can still land in the human conversation.
    Recorded here rather than papered over -- the alternative is correlating
    mail to sessions by timestamp, which is a guess wearing a fact's clothes.
    """
    if not session:
        return (HUMAN_AGENT, "")
    row = conn.execute(
        "SELECT channel, sender FROM messages"
        " WHERE session_id = ? AND direction = ?"
        " ORDER BY sent_at DESC, id DESC LIMIT 1",
        (session, INBOUND)).fetchone()
    if row is None:
        return (HUMAN_AGENT, "")
    return (row["channel"], row["sender"] or "")


def ingest_spool(conn: sqlite3.Connection,
                 directory: "Path | None" = None) -> SeedReport:
    """Fold captured events into the store.

    Spool files are kept, not consumed. Re-reading them is free -- the natural
    key rejects what is already stored -- and a crash between reading and
    committing would otherwise lose the only copy.
    """
    report = SeedReport(SOURCE_HOOK)
    base = Path(directory) if directory is not None else spool_dir()
    present = install_manifest.dir_present(base)
    if present is False:
        report.absent = f"nothing captured yet at {base}"
        return report
    if present is None:
        report.errors.append(
            f"could not determine whether {base} exists (permissions?)")
        return report
    for path in sorted(base.glob("*.jsonl")):
        # The channel of the last thing said *to* each session, so a reply can
        # be filed against the conversation it belongs to. An outbound event
        # carries no sender of its own, and defaulting every one of them to
        # `human-agent` put the agent's answers to peers into the human's
        # conversation -- the one view the human asked to keep separate.
        answering: dict = {}
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError as exc:
            report.errors.append(f"{path.name}: {exc}")
            continue
        for number, line in enumerate(lines, 1):
            if not line.strip():
                continue
            try:
                event = json.loads(line)
            except ValueError:
                # A partially written final line is expected: the writer is a
                # live session and may be mid-append. Counted, not fatal.
                report.skip("unparseable line")
                continue
            if not isinstance(event, dict):
                report.skip("not an event object")
                continue
            body = str(event.get("body") or "")
            direction = str(event.get("direction") or "")
            if direction not in (INBOUND, OUTBOUND):
                report.skip("unknown direction")
                continue
            if not body.strip():
                report.skip("empty body")
                continue
            if direction == INBOUND and peer_sender(body) is not None:
                # Held by mail -- but remember what it was, so the reply to it
                # is not filed as human conversation.
                answering[str(event.get("session_id") or "")] = (
                    AGENT_AGENT, peer_sender(body))
                report.skip("peer message, held by operator mail")
                continue
            identity = str(event.get("id") or f"{path.stem}:{number}")
            session = str(event.get("session_id") or "")
            actor = channel = None
            sender = recipient = ""
            if direction == INBOUND:
                actor, channel, sender = classify(body)
                answering[session] = (channel, sender)
            else:
                channel, recipient = (answering.get(session)
                                      or _prior_channel(conn, session))
                actor = AGENT
            added = record(
                conn, source=SOURCE_HOOK, source_id=identity, body=body,
                direction=direction, sent_at=str(event.get("sent_at") or ""),
                cwd=str(event.get("cwd") or ""),
                session_id=session,
                actor=actor, channel=channel, sender=sender,
                recipient=recipient)
            report.added += 1 if added else 0
            report.duplicate += 0 if added else 1
    conn.commit()
    return report


def seed_all(conn: sqlite3.Connection) -> list[SeedReport]:
    """Every source, spool first.

    Order is load-bearing, not cosmetic. The session store and the capture
    hook both see the same turn, and `seed_session_store` skips what the hook
    already holds -- so the hook has to have been read for that test to have
    anything to answer with. Run the other way round, the very first seed on a
    machine with the extension installed files every captured turn twice.
    """
    return [ingest_spool(conn), seed_operator_mail(conn),
            seed_session_store(conn)]


# --------------------------------------------------------------------------
# Reading
# --------------------------------------------------------------------------

#: Values the viewer will accept for `channel`, `direction` and `actor`.
#: Filters are matched against these rather than interpolated, so a query
#: string cannot reach the SQL.
_ENUMS = {
    "channel": (HUMAN_AGENT, AGENT_AGENT),
    "direction": (INBOUND, OUTBOUND),
    "actor": (HUMAN, AGENT, SYSTEM),
}


def _fts_query(text: str) -> str:
    """Turn user input into an FTS5 MATCH expression that cannot be malformed.

    Every term is quoted and the terms are ANDed. FTS5's query language treats
    ``-``, ``*``, ``:``, ``(`` and ``"`` as syntax, so a search for a filename
    or a flag -- exactly what gets searched for here -- raises rather than
    returning nothing, and an error page for `--force` would be absurd.

    Split on ``[\\W_]+`` rather than ``[^\\w]+`` because the two disagree about
    one character and the disagreement is silent. Python's ``\\w`` includes
    ``_``; FTS5's unicode61 tokeniser treats it as a separator. So a search for
    ``_`` produced the term ``_``, this returned the non-empty expression
    ``"_"``, the caller took that as "FTS can answer this" -- and FTS then
    tokenised it away to an empty phrase and matched nothing. Two rows on the
    test machine contain ``_`` and the search for it found neither, with no
    error and no fallback. Splitting on FTS's own separator set makes the
    emptiness test agree with the engine that has to run the query.
    """
    terms = [t for t in re.split(r"[\W_]+", text) if t]
    return " AND ".join('"' + t + '"' for t in terms)


def _like_term(text: str) -> str:
    """Escape the wildcards LIKE would otherwise read as syntax.

    ``%`` and ``_`` are LIKE's own metacharacters, so an unescaped search for
    ``100%`` matches every row whose body contains ``100`` followed by
    anything, and one for ``a_b`` matches ``axb``. Both return *more* rows
    than asked for, which is the failure that does not look like one.
    """
    return (text.replace("\\", "\\\\")
                .replace("%", "\\%")
                .replace("_", "\\_"))


def query(conn: sqlite3.Connection, *, search: str = "", project: str = "",
          channel: str = "", direction: str = "", actor: str = "",
          instance: str = "", date_from: str = "", date_to: str = "",
          session_id: str = "", asks: bool = False,
          limit: int = 200, offset: int = 0) -> list[dict]:
    """Messages matching the given filters, newest first."""
    where: list[str] = []
    params: list[object] = []

    if asks:
        # In SQL, not in the caller. The viewer filtered the returned page,
        # which applies the filter *after* LIMIT: one old question behind 200
        # newer statements returned nothing at all, and "no questions" is
        # indistinguishable from "none in the last 200 rows".
        where.append("m.asks = 1")

    if search.strip():
        if "\x00" in search:
            # A NUL cannot occur in a stored body -- these come from JSON and
            # from SQLite TEXT -- so this search matches nothing. Saying that
            # explicitly matters because the alternative is not "no rows": a
            # NUL in a bound LIKE parameter truncates the pattern at the NUL,
            # so `%\x00%` degenerates to `%` and every row comes back. That is
            # the same match-everything failure this branch was rewritten to
            # remove, reachable through the rewrite.
            where.append("1 = 0")
        else:
            expr = _fts_query(search) if search_mode(conn) == "fts" else ""
            if expr:
                where.append("m.id IN (SELECT rowid FROM messages_fts "
                             "WHERE messages_fts MATCH ?)")
                params.append(expr)
            else:
                # Either there is no FTS index, or the search is all
                # punctuation -- `(`, `*`, `-->` -- which FTS5's tokeniser
                # discards entirely, leaving an empty MATCH expression.
                #
                # Dropping the predicate here is what this branch used to do,
                # and it is the worst of the three options: the user searches
                # for `(`, every row comes back, and a result set that means
                # "no filter was applied" is indistinguishable from one that
                # means "everything matched". Returning nothing would at least
                # be honest, but it is still wrong -- there really are rows
                # containing `(`, and the substring path can find them. So
                # punctuation searches take the same route as a machine with
                # no FTS5, which also keeps the two modes returning the same
                # rows for the same query.
                where.append("m.body LIKE ? ESCAPE '\\'")
                params.append(f"%{_like_term(search.strip())}%")

    for column, value in (("project", project), ("instance", instance),
                          ("session_id", session_id)):
        if value:
            where.append(f"m.{column} = ?")
            params.append(value)

    for column, value in (("channel", channel), ("direction", direction),
                          ("actor", actor)):
        if value:
            if value not in _ENUMS[column]:
                raise ConversationError(f"unknown {column}: {value!r}")
            where.append(f"m.{column} = ?")
            params.append(value)

    # Dates are compared on the 10-character prefix so a caller can pass a day
    # without having to know how the timestamp is spelled.
    if date_from:
        where.append("substr(m.sent_at, 1, 10) >= ?")
        params.append(date_from[:10])
    if date_to:
        where.append("substr(m.sent_at, 1, 10) <= ?")
        params.append(date_to[:10])

    clause = (" WHERE " + " AND ".join(where)) if where else ""
    sql = (f"SELECT m.* FROM messages m{clause} "
           f"ORDER BY m.sent_at DESC, m.id DESC LIMIT ? OFFSET ?")
    params.extend([max(1, min(int(limit), 1000)), max(0, int(offset))])
    return [dict(r) for r in conn.execute(sql, params)]


def projects(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute(
        "SELECT project, COUNT(*) AS messages,"
        "       MIN(substr(sent_at, 1, 10)) AS first_day,"
        "       MAX(substr(sent_at, 1, 10)) AS last_day"
        "  FROM messages WHERE project <> ''"
        " GROUP BY project ORDER BY MAX(sent_at) DESC")
    return [dict(r) for r in rows]


def days(conn: sqlite3.Connection, project: str = "") -> list[dict]:
    sql = ("SELECT substr(sent_at, 1, 10) AS day, COUNT(*) AS messages"
           "  FROM messages")
    params: list[object] = []
    if project:
        sql += " WHERE project = ?"
        params.append(project)
    sql += " GROUP BY day ORDER BY day DESC"
    return [dict(r) for r in conn.execute(sql, params)]


def instances(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT DISTINCT instance FROM messages"
        " WHERE instance <> '' ORDER BY instance")
    return [r["instance"] for r in rows]


def summary(conn: sqlite3.Connection) -> dict:
    row = conn.execute(
        "SELECT COUNT(*) AS messages,"
        "       COUNT(DISTINCT project) AS projects,"
        "       COUNT(DISTINCT session_id) AS sessions,"
        "       MIN(substr(sent_at, 1, 10)) AS first_day,"
        "       MAX(substr(sent_at, 1, 10)) AS last_day"
        "  FROM messages").fetchone()
    out = dict(row) if row else {}
    by_channel = conn.execute(
        "SELECT channel, actor, COUNT(*) AS n FROM messages"
        " GROUP BY channel, actor")
    out["breakdown"] = [dict(r) for r in by_channel]
    out["search_mode"] = search_mode(conn)
    return out
